Description: >
    NGINX and application tasks running in an ECS service. Load balancer directs requests to the two services.

Parameters: 
    Cluster:
        Description: The ECS cluster ID these services will run on
        Type: String

    DesiredCount:
        Description: Amount of instances of task to run
        Type: Number
        Default: 2

    ListenerHTTP:
        Description: HTTP ALB Listener
        Type: String

    ListenerHTTPS:
        Description: HTTPS ALB Listener
        Type: String

    Path:
        Description: The path to register with the ALB
        Type: String
        Default: /

  # APP SPECIFIC VARIABLES 

    ECR:
        Description: ECR
        Type: String

    APPURL:
        Type: String

    DBCONNECTION:
        Type: String

    DBHOST:
        Type: String

    DBPORT:
        Type: String

    DBDATABASE:
        Type: String

    DBUSERNAME:
        Type: String

    DBPASSWORD:
        Type: String

    MAILDRIVER:
        Type: String

    MAILHOST:
        Type: String

    MAILPORT:
        Type: String

    MAILUSERNAME:
        Type: String

    MAILPASSWORD:
        Type: String

    MAILFROMADDRESS:
        Type: String

    MAILFROMNAME:
        Type: String

    FILESYSTEMDRIVER:
        Type: String

    AWS_BUCKET:
        Type: String

Resources:
    Service: 
        Type: AWS::ECS::Service
        DependsOn:
          - ListenerRuleHTTPS
        Properties: 
            Cluster: !Ref Cluster
            Role: !Ref ServiceRole
            DesiredCount: !Ref DesiredCount
            TaskDefinition: !Ref TaskDefinition
            LoadBalancers: 
                - ContainerName: nginx
                  ContainerPort: 80
                  TargetGroupArn: !Ref TargetGroup

    ServiceWorkers:
        Type: AWS::ECS::Service
        Properties:
            Cluster: !Ref Cluster
            DesiredCount: 1
            TaskDefinition: !Ref TaskDefinitionWorker

    ServiceRedirect:
        Type: AWS::ECS::Service
        DependsOn:
          - ListenerRuleHTTP
        Properties:
            Cluster: !Ref Cluster
            Role: !Ref ServiceRole
            DesiredCount: 1
            TaskDefinition: !Ref TaskDefinitionRedirectHTTPtoHTTPS
            LoadBalancers:
                - ContainerName: nginx-to-https
                  ContainerPort: 80
                  TargetGroupArn: !Ref TargetGroupRedirectHTTPSToHTTP

    TaskDefinitionRedirectHTTPtoHTTPS:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: nginx-to-https
            ContainerDefinitions:
                - Name: nginx-to-https
                  Essential: true
                  Image: getlionel/nginx-to-https
                  Memory: 128
                  PortMappings:
                    - ContainerPort: 80

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: nginx
            ContainerDefinitions:
                - Name: nginx
                  Essential: true
                  Image: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ ":", [ !Join [ "/", [ "amazonaws.com", !Ref ECR ] ], "nginx" ] ] ] ]
                  Memory: 128
                  PortMappings:
                    - ContainerPort: 80
                  Links:
                    - app
                - Name: app
                  Essential: true
                  Image: !Join [ ".", [ !Ref "AWS::AccountId", "dkr.ecr", !Ref "AWS::Region", !Join [ ":", [ !Join [ "/", [ "amazonaws.com", !Ref ECR ] ], "app" ] ] ] ]
                  Memory: 128
                  Environment:
                    - Name: APP_NAME
                      Value: Laravel
                    - Name: APP_ENV
                      Value: production
                    - Name: APP_DEBUG
                      Value: false
                    - Name: APP_LOG_LEVEL
                      Value: error
                    - Name: APP_KEY
                      Value: base64:h2ASblVGbCXbC1buJ8KToZkKIEY69GSiutkAeGo77B0=
                    - Name: APP_URL
                      Value: !Ref APPURL
                    - Name: DB_CONNECTION
                      Value: !Ref DBCONNECTION
                    - Name: DB_HOST
                      Value: !Ref DBHOST
                    - Name: DB_PORT
                      Value: !Ref DBPORT
                    - Name: DB_DATABASE
                      Value: !Ref DBDATABASE
                    - Name: DB_USERNAME
                      Value: !Ref DBUSERNAME
                    - Name: DB_PASSWORD
                      Value: !Ref DBPASSWORD
                    - Name: CACHE_DRIVER
                      Value: file
                    - Name: SESSION_DRIVER
                      Value: database
                    - Name: MAIL_DRIVER
                      Value: !Ref MAILDRIVER
                    - Name: MAIL_HOST
                      Value: !Ref MAILHOST
                    - Name: MAIL_PORT
                      Value: !Ref MAILPORT
                    - Name: MAIL_USERNAME
                      Value: !Ref MAILUSERNAME
                    - Name: MAIL_PASSWORD
                      Value: !Ref MAILPASSWORD
                    - Name: MAIL_FROM_ADDRESS
                      Value: !Ref MAILFROMADDRESS
                    - Name: MAIL_FROM_NAME
                      Value: !Ref MAILFROMNAME
                    - Name: FILESYSTEM_DRIVER
                      Value: !Ref FILESYSTEMDRIVER
                    - Name: AWS_REGION
                      Value: !Sub ${AWS::Region}
                    - Name: AWS_BUCKET
                      Value: !Ref AWS_BUCKET
                    - Name: AWS_ACCOUNT_ID
                      Value: !Ref AWS::AccountId

    TargetGroupRedirectHTTPSToHTTP:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Port: 80
            Protocol: HTTP
            Matcher:
                HttpCode: 200-301
            HealthCheckIntervalSeconds: 10
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 2

    ListenerRuleHTTP:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref ListenerHTTP
            Priority: 1
            Conditions:
                - Field: path-pattern
                  Values:
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroupRedirectHTTPSToHTTP
                  Type: forward

    ListenerRuleHTTPS:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            ListenerArn: !Ref ListenerHTTPS
            Priority: 1
            Conditions:
                - Field: path-pattern
                  Values:
                    - !Ref Path
            Actions:
                - TargetGroupArn: !Ref TargetGroup
                  Type: forward